services:
  web_institucional:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kepler_institutional_demo
    # 01_manifiesto_core: Control de recursos (Límites estrictos)
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
    # Solución al hardcoding de IP usando fallbacks seguros:
    ports:
      - "${HOST_IP:-127.0.0.1}:${HOST_PORT:-8080}:80"
    #restart: unless-stopped
    restart: always
    # Red aislada para seguridad
    networks:
      - kepler-net

networks:
  kepler-net:
    driver: bridge
